### ISSUE TITLE
Different kinds of subscriptions

### ISSUE THREAD

**Issue by Magomogo** [group-life/core#21]
Please implement:

* Subscription\OneTime - one visit any day
* Subscription\FixedTime - one visit exact day
* Subscription\Activity - one activity.

Method `Activity::subscribe` should accept any subscription polymorphically, it means depend on some interface.

**Comment by Lehersun** [comment]
Based on the description, Subscription's behavior completely repeats the behavior of Schedule, can we use it?

**Comment by Magomogo** [comment]
> Based on the description, Subscription's behavior completely repeats the behavior of Schedule, can we use it?

I'm not sure if so. IMHO it should have different public interface.
